"""Embeddings + semantic search (RAG retrieval).

Embeddings are generated by Ollama (nomic-embed-text — free, local, good
quality) and stored as packed float32 BLOBs on each entry. Search uses an
in-Python cosine scan — instant at single-user diary scale (sqlite-vec is
loaded by database.py for future use on bigger datasets).

If Ollama is unreachable when an entry is saved, the entry still saves;
embedding is retried next time the entry is polished or edited.
"""
import math
import struct

import httpx
from sqlalchemy.orm import Session

from ..config import settings
from ..models import Entry


def pack(vec: list[float]) -> bytes:
    return struct.pack(f"{len(vec)}f", *vec)


def unpack(blob: bytes) -> list[float]:
    return list(struct.unpack(f"{len(blob) // 4}f", blob))


async def embed(text: str) -> list[float] | None:
    """Return an embedding via Ollama, or None if unavailable."""
    try:
        async with httpx.AsyncClient(timeout=60) as client:
            r = await client.post(
                f"{settings.OLLAMA_BASE_URL}/api/embeddings",
                json={"model": settings.OLLAMA_EMBED_MODEL, "prompt": text},
            )
            r.raise_for_status()
            return r.json()["embedding"]
    except Exception:
        # Ollama down/unreachable, proxy issues, malformed response… embedding
        # is always best-effort; callers must proceed without it.
        return None


async def embed_entry(entry: Entry, db: Session) -> bool:
    text = f"{entry.title}\n{entry.display_text}".strip()
    vec = await embed(text)
    if vec is None:
        return False
    entry.embedding = pack(vec)
    entry.embedding_model = settings.OLLAMA_EMBED_MODEL
    db.commit()
    return True


def _cosine(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(y * y for y in b))
    return dot / (na * nb) if na and nb else 0.0


async def search(db: Session, query: str, top_k: int = 6) -> list[tuple[Entry, float]]:
    """Semantic search over all embedded entries. Returns (entry, score) pairs."""
    qvec = await embed(query)
    if qvec is None:
        return []
    rows = db.query(Entry).filter(Entry.embedding.isnot(None)).all()
    scored = [(e, _cosine(qvec, unpack(e.embedding))) for e in rows]
    scored.sort(key=lambda t: t[1], reverse=True)
    return scored[:top_k]


def context_block(entry: Entry) -> str:
    topic = f" [{entry.topic.name}]" if entry.topic else ""
    return f"Entry {entry.entry_date.isoformat()}{topic} — {entry.title}\n{entry.display_text}"
